import {
  MODE_STATIC,
  MODE_PROPERTY,
  CONDITION_ALWAYS,
  CONDITION_IF_SET,
  CONDITION_UNLESS_SET,
} from './constants';

/**
 * Loads the settings module with a mocked config.json. The file is generated by the SDK and does
 * not exist in the repository, so the mock has to be virtual.
 * @param {Object} config The content of the generated config.json.
 * @returns {Object} The exports of the settings module.
 */
const loadSettings = (config) => {
  jest.resetModules();
  jest.doMock('./config.json', () => config, { virtual: true });

  // eslint-disable-next-line global-require
  return require('./settings');
};

describe('settings', () => {
  afterEach(() => {
    jest.resetModules();
  });

  describe('defaults', () => {
    it('should fall back to defaults for an empty config', () => {
      const { settings } = loadSettings({});

      expect(settings).toEqual({
        mode: MODE_STATIC,
        text: '',
        property: '',
        conditionMode: CONDITION_ALWAYS,
        conditionProperty: '',
        conditionValues: [],
        fallbackProperty: '',
      });
    });

    it('should fall back to defaults for unsupported values', () => {
      const { settings } = loadSettings({
        mode: 'somethingElse',
        conditionMode: 'never',
      });

      expect(settings.mode).toBe(MODE_STATIC);
      expect(settings.conditionMode).toBe(CONDITION_ALWAYS);
    });

    it('should fall back to defaults for values of a wrong type', () => {
      const { settings } = loadSettings({
        mode: 1,
        text: null,
        property: false,
        conditionValues: ['yes'],
      });

      expect(settings.mode).toBe(MODE_STATIC);
      expect(settings.text).toBe('');
      expect(settings.property).toBe('');
      expect(settings.conditionValues).toEqual([]);
    });
  });

  describe('parsing', () => {
    it('should keep supported values', () => {
      const { settings } = loadSettings({
        mode: MODE_PROPERTY,
        conditionMode: CONDITION_UNLESS_SET,
      });

      expect(settings.mode).toBe(MODE_PROPERTY);
      expect(settings.conditionMode).toBe(CONDITION_UNLESS_SET);
    });

    it('should trim texts', () => {
      const { settings } = loadSettings({
        mode: `  ${MODE_PROPERTY}  `,
        text: '  Delivered within 2-3 business days  ',
        property: ' Delivery time ',
        conditionProperty: ' Preorder ',
        fallbackProperty: ' deliveryTime ',
      });

      expect(settings.mode).toBe(MODE_PROPERTY);
      expect(settings.text).toBe('Delivered within 2-3 business days');
      expect(settings.property).toBe('Delivery time');
      expect(settings.conditionProperty).toBe('Preorder');
      expect(settings.fallbackProperty).toBe('deliveryTime');
    });

    it('should split the condition values and drop empty entries', () => {
      const { settings } = loadSettings({
        conditionValues: ' yes , true ,, 1 , ',
      });

      expect(settings.conditionValues).toEqual(['yes', 'true', '1']);
    });
  });

  describe('isEnabled', () => {
    it('should be disabled for an empty config', () => {
      expect(loadSettings({}).isEnabled).toBe(false);
    });

    it('should be enabled for a static text', () => {
      expect(loadSettings({
        mode: MODE_STATIC,
        text: 'Delivered within 2-3 business days',
      }).isEnabled).toBe(true);
    });

    it('should be disabled when the static text is missing', () => {
      expect(loadSettings({
        mode: MODE_STATIC,
        property: 'Delivery time',
      }).isEnabled).toBe(false);
    });

    it('should be enabled for a property text', () => {
      expect(loadSettings({
        mode: MODE_PROPERTY,
        property: 'Delivery time',
      }).isEnabled).toBe(true);
    });

    it('should be disabled when the property is missing', () => {
      expect(loadSettings({
        mode: MODE_PROPERTY,
        text: 'Delivered within 2-3 business days',
      }).isEnabled).toBe(false);
    });

    it('should be enabled for a condition with a property', () => {
      expect(loadSettings({
        mode: MODE_STATIC,
        text: 'Delivered within 2-3 business days',
        conditionMode: CONDITION_IF_SET,
        conditionProperty: 'Preorder',
      }).isEnabled).toBe(true);
    });

    it('should be disabled when the condition property is missing', () => {
      expect(loadSettings({
        mode: MODE_STATIC,
        text: 'Delivered within 2-3 business days',
        conditionMode: CONDITION_UNLESS_SET,
      }).isEnabled).toBe(false);
    });
  });
});
